id: P009416
initial_creation_type: ocr
source_metadata:
  id: bdr:W29516
  title: ཤར་པའི་ཆོས་འབྱུང་དང་མེས་རབས
  author: ''
  volumes:
    4f953b00681146a18faed79ce257f60f:
      image_group_id: I1GS66371
      title: ''
      volume_number: 1
      total_pages: 91
