id: IDA88A6B0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T22:02:14+00:00'
last_modified: '2022-06-08T10:52:51.940416+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29516
  title: ཤར་པའི་ཆོས་འབྱུང་དང་མེས་རབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    67E9:
      image_group_id: I1GS66371
      title: ''
      total_pages: 91
      order: 1
      base_file: 67E9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
